project:
  type: website
  output-dir: docs

website:
  title: "Macroecología: integrando espacio y tiempo para entender la biodiversidad"
  favicon: maevolab.png
  
  navbar:
    background: "#01497c"
    logo: cursologo.png
    pinned: true
    align: center
    left: 
      - href: index.qmd
        text: Inicio

  
  page-footer:
    center: |
      <div style="display:flex; justify-content:center; gap:30px;">
        <img src="udea.png" alt="Logo UdeA" height="80"/>
        <img src="inecol.png" alt="Logo Inecol" height="80"/>
        <img src="maevolab.png" alt="Logo Maevolab" height="80"/>
        <img src="ecoevo.png" alt="Logo Ecoevo" height="80"/>
      </div>

format:
  html:
    theme: 
      light: [flatly, web_styles.scss]
    toc: true
    
execute:
  freeze: auto
