project:
  type: website
  output-dir: docs

website:
  title: "Macroecología: integrando espacio y tiempo para entender la biodiversidad"
  favicon: maevolab.png
  
  navbar:
    background: "#01497c"
    logo: cursologo.png
    pinned: true
    align: center
    left: 
      - href: index.qmd
        text: Inicio

  
  page-footer:
    right: |
      <img src="logo_footer.png" alt="Logo Instituciones" height="30"/>


format:
  html:
    theme: 
      light: [flatly, web_styles.scss]
    toc: true
    
execute:
  freeze: auto
